### ISSUE TITLE
Enable gh-pages

### ISSUE THREAD

**Issue by hfu** [madefor/tile-riot#1]
@miya0001 (or @cognitom or @takahashim in madefor owners), would you kindly enable gh-pages of this repository, where the source is "master branch" as in the image below, so that the examples can be demonstrated from them?

<img width="745" alt="2017-04-18 15 32 49" src="https://cloud.githubusercontent.com/assets/18297/25117408/faa5e5ca-244c-11e7-96f6-5c6d2f13560e.png">

**Comment by takahashim** [comment]
🙆

**Comment by takahashim** [comment]
done.
https://madefor.github.io/tile-riot/

**Comment by hfu** [comment]
Thanks @takahashim , it works!
https://madefor.github.io/tile-riot/

**Comment by hfu** [comment]
And I am going to proceed to the development... ;-)
